<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use App\Models\NationalitieslistModel;

class NationalitieslistSeeder extends Seeder
{
    public function run()
    {
        $nationality = new NationalitieslistModel;
        $data = [
            [
                'country_name' => 'Afghanistan',
                'nationality' => 'Afghan',
                'alpha_2_code' => 'AF',
                'alpha_3_code' => 'AFG',
                'num_code' =>4,
            ],
            [
                'country_name' => 'Albania',
                'nationality' => 'Albanian',
                'alpha_2_code' => 'AL',
                'alpha_3_code' => 'ALB',
                'num_code' =>8,
            ],
            [
                'country_name' => 'Algeria',
                'nationality' => 'Algerian',
                'alpha_2_code' => 'DZ',
                'alpha_3_code' => 'DZA',
                'num_code' =>12,
            ],
            [
                'country_name' => 'Andorra',
                'nationality' => 'Andorran',
                'alpha_2_code' => 'AD',
                'alpha_3_code' => 'AND',
                'num_code' =>20,
            ],
            [
                'country_name' => 'Angola',
                'nationality' => 'Angolan',
                'alpha_2_code' => 'AO',
                'alpha_3_code' => 'AGO',
                'num_code' =>24,
            ],
            [
                'country_name' => 'Anguilla',
                'nationality' => 'Anguillan',
                'alpha_2_code' => 'AI',
                'alpha_3_code' => 'AIA',
                'num_code' =>660,
            ],
            [
                'country_name' => 'Argentina',
                'nationality' => 'Argentine',
                'alpha_2_code' => 'AR',
                'alpha_3_code' => 'ARG',
                'num_code' =>32,
            ],
            [
                'country_name' => 'Armenia',
                'nationality' => 'Armenian',
                'alpha_2_code' => 'AM',
                'alpha_3_code' => 'ARM',
                'num_code' =>51,
            ],
            [
                'country_name' => 'Australia',
                'nationality' => 'Australian',
                'alpha_2_code' => 'AU',
                'alpha_3_code' => 'AUS',
                'num_code' =>36,
            ],
            [
                'country_name' => 'Austria',
                'nationality' => 'Austrian',
                'alpha_2_code' => 'AT',
                'alpha_3_code' => 'AUT',
                'num_code' =>40,
            ],
            [
                'country_name' => 'Azerbaijan',
                'nationality' => 'Azerbaijani',
                'alpha_2_code' => 'AZ',
                'alpha_3_code' => 'AZE',
                'num_code' =>31,
            ],
            [
                'country_name' => 'Bahamas',
                'nationality' => 'Bahamian',
                'alpha_2_code' => 'BS',
                'alpha_3_code' => 'BHS',
                'num_code' =>44,
            ],
            [
                'country_name' => 'Bahrain',
                'nationality' => 'Bahraini',
                'alpha_2_code' => 'BH',
                'alpha_3_code' => 'BHR',
                'num_code' =>48,
            ],
            [
                'country_name' => 'Bangladesh',
                'nationality' => 'Bangladeshi',
                'alpha_2_code' => 'BD',
                'alpha_3_code' => 'BGD',
                'num_code' =>50,
            ],
            // [
            //     'country_name' => 'Barbados',
            //     'nationality' => 'Barbadian',
            //     'alpha_2_code' => 'BB',
            //     'alpha_3_code' => 'BRB',
            //     'num_code' =>52,
            // ],
            [
                'country_name' => 'Belarus',
                'nationality' => 'Belarusian',
                'alpha_2_code' => 'BY',
                'alpha_3_code' => 'BLR',
                'num_code' =>112,
            ],
            [
                'country_name' => 'Belgium',
                'nationality' => 'Belgian',
                'alpha_2_code' => 'BE',
                'alpha_3_code' => 'BEL',
                'num_code' =>56,
            ],
            [
                'country_name' => 'Belize',
                'nationality' => 'Belizean',
                'alpha_2_code' => 'BZ',
                'alpha_3_code' => 'BLZ',
                'num_code' =>84,
            ],
            [
                'country_name' => 'Benin',
                'nationality' => 'Beninese',
                'alpha_2_code' => 'BJ',
                'alpha_3_code' => 'BEN',
                'num_code' =>204,
            ],
            [
                'country_name' => 'Bermuda',
                'nationality' => 'Bermudian',
                'alpha_2_code' => 'BM',
                'alpha_3_code' => 'BMU',
                'num_code' =>60,
            ],
            [
                'country_name' => 'Bhutan',
                'nationality' => 'Bhutanese',
                'alpha_2_code' => 'BT',
                'alpha_3_code' => 'BTN',
                'num_code' =>64,
            ],
            [
                'country_name' => 'Bolivia (Plurinational State of)',
                'nationality' => 'Bolivian',
                'alpha_2_code' => 'BO',
                'alpha_3_code' => 'BOL',
                'num_code' =>68,
            ],
            // [
            //     'country_name' => 'Bonaire, Sint Eustatius and Saba',
            //     'nationality' => 'Bonaire',
            //     'alpha_2_code' => 'BQ',
            //     'alpha_3_code' => 'BES',
            //     'num_code' =>535,
            // ],
            [
                'country_name' => 'Bosnia and Herzegovina',
                'nationality' => 'Bosnian/Herzegovinian',
                'alpha_2_code' => 'BA',
                'alpha_3_code' => 'BIH',
                'num_code' =>70,
            ],
            [
                'country_name' => 'Botswana',
                'nationality' => 'Botswanan',
                'alpha_2_code' => 'BW',
                'alpha_3_code' => 'BWA',
                'num_code' =>72,
            ],
            [
                'country_name' => 'Brazil',
                'nationality' => 'Brazilian',
                'alpha_2_code' => 'BR',
                'alpha_3_code' => 'BRA',
                'num_code' =>76,
            ],
            [
                'country_name' => 'Bulgaria',
                'nationality' => 'Bulgarian',
                'alpha_2_code' => 'BG',
                'alpha_3_code' => 'BGR',
                'num_code' =>100,
            ],
            [
                'country_name' => 'Burkina Faso',
                'nationality' => 'Burkinabé',
                'alpha_2_code' => 'BF',
                'alpha_3_code' => 'BFA',
                'num_code' =>854,
            ],
            [
                'country_name' => 'Burundi',
                'nationality' => 'Burundian',
                'alpha_2_code' => 'BI',
                'alpha_3_code' => 'BDI',
                'num_code' =>108,
            ],
            [
                'country_name' => 'Cambodia',
                'nationality' => 'Cambodian',
                'alpha_2_code' => 'KH',
                'alpha_3_code' => 'KHM',
                'num_code' =>116,
            ],
            [
                'country_name' => 'Cameroon',
                'nationality' => 'Cameroonian',
                'alpha_2_code' => 'CM',
                'alpha_3_code' => 'CMR',
                'num_code' =>120,
            ],
            [
                'country_name' => 'Canada',
                'nationality' => 'Canadian',
                'alpha_2_code' => 'CA',
                'alpha_3_code' => 'CAN',
                'num_code' =>124,
            ],
            [
                'country_name' => 'Cape Verde',
                'nationality' => 'Cape Verdean',
                'alpha_2_code' => 'CV',
                'alpha_3_code' => 'CPV',
                'num_code' =>132,
            ],
            [
                'country_name' => 'Cayman Islands',
                'nationality' => 'Cayman Islander',
                'alpha_2_code' => 'KY',
                'alpha_3_code' => 'CYM',
                'num_code' =>136,
            ],
            [
                'country_name' => 'Central African Republic',
                'nationality' => 'Central African',
                'alpha_2_code' => 'CF',
                'alpha_3_code' => 'CAF',
                'num_code' =>140,
            ],
            [
                'country_name' => 'Chad',
                'nationality' => 'Chadian',
                'alpha_2_code' => 'TD',
                'alpha_3_code' => 'TCD',
                'num_code' =>148,
            ],
            [
                'country_name' => 'Chile',
                'nationality' => 'Chilean',
                'alpha_2_code' => 'CL',
                'alpha_3_code' => 'CHL',
                'num_code' =>152,
            ],
            [
                'country_name' => 'China',
                'nationality' => 'Chinese',
                'alpha_2_code' => 'CN',
                'alpha_3_code' => 'CHN',
                'num_code' =>156,
            ],
            [
                'country_name' => 'Christmas Island',
                'nationality' => 'Christmas Island',
                'alpha_2_code' => 'CX',
                'alpha_3_code' => 'CXR',
                'num_code' =>162,
            ],
            [
                'country_name' => 'Cocos (Keeling) Islands',
                'nationality' => 'Cocos Island',
                'alpha_2_code' => 'CC',
                'alpha_3_code' => 'CCK',
                'num_code' =>166,
            ],
            [
                'country_name' => 'Colombia',
                'nationality' => 'Colombian',
                'alpha_2_code' => 'CO',
                'alpha_3_code' => 'COL',
                'num_code' =>170,
            ],
            [
                'country_name' => 'Comoros',
                'nationality' => 'Comoran',
                'alpha_2_code' => 'KM',
                'alpha_3_code' => 'COM',
                'num_code' =>174,
            ],
            [
                'country_name' => 'Congo (Republic of the)',
                'nationality' => 'Congolese(Congo)',
                'alpha_2_code' => 'CG',
                'alpha_3_code' => 'COG',
                'num_code' =>178,
            ],
            [
                'country_name' => 'Congo (Democratic Republic of the)',
                'nationality' => 'Congolese(DRC)',
                'alpha_2_code' => 'CD',
                'alpha_3_code' => 'COD',
                'num_code' =>180,
            ],
            [
                'country_name' => 'Cook Islands',
                'nationality' => 'Cook Islander',
                'alpha_2_code' => 'CK',
                'alpha_3_code' => 'COK',
                'num_code' =>184,
            ],
            [
                'country_name' => 'Costa Rica',
                'nationality' => 'Costa Rican',
                'alpha_2_code' => 'CR',
                'alpha_3_code' => 'CRI',
                'num_code' =>188,
            ],
            [
                'country_name' => "Côte d'Ivoire",
                'nationality' => 'Ivorian',
                'alpha_2_code' => 'CI',
                'alpha_3_code' => 'CIV',
                'num_code' =>384,
            ],
            [
                'country_name' => 'Croatia',
                'nationality' => 'Croatian',
                'alpha_2_code' => 'HR',
                'alpha_3_code' => 'HRV',
                'num_code' =>191,
            ],
            [
                'country_name' => 'Cuba',
                'nationality' => 'Cuban',
                'alpha_2_code' => 'CU',
                'alpha_3_code' => 'CUB',
                'num_code' =>192,
            ],
            [
                'country_name' => 'Curaçao',
                'nationality' => 'Curaçaoan',
                'alpha_2_code' => 'CW',
                'alpha_3_code' => 'CUW',
                'num_code' =>531,
            ],
            [
                'country_name' => 'Cyprus',
                'nationality' => 'Cypriot',
                'alpha_2_code' => 'CY',
                'alpha_3_code' => 'CYP',
                'num_code' =>196,
            ],
            [
                'country_name' => 'Czech Republic',
                'nationality' => 'Czech',
                'alpha_2_code' => 'CZ',
                'alpha_3_code' => 'CZE',
                'num_code' =>203,
            ],
            [
                'country_name' => 'Denmark',
                'nationality' => 'Danish',
                'alpha_2_code' => 'DK',
                'alpha_3_code' => 'DNK',
                'num_code' =>208,
            ],
            [
                'country_name' => 'Djibouti',
                'nationality' => 'Djiboutian',
                'alpha_2_code' => 'DJ',
                'alpha_3_code' => 'DJI',
                'num_code' =>262,
            ],
            [
                'country_name' => 'Dominica',
                'nationality' => 'Dominican',
                'alpha_2_code' => 'DM',
                'alpha_3_code' => 'DMA',
                'num_code' =>212,
            ],
            [
                'country_name' => 'Dominican Republic',
                'nationality' => 'Dominican',
                'alpha_2_code' => 'DO',
                'alpha_3_code' => 'DOM',
                'num_code' =>214,
            ],
            [
                'country_name' => 'Ecuador',
                'nationality' => 'Ecuadorian',
                'alpha_2_code' => 'EC',
                'alpha_3_code' => 'ECU',
                'num_code' =>218,
            ],
            [
                'country_name' => 'Egypt',
                'nationality' => 'Egyptian',
                'alpha_2_code' => 'EG',
                'alpha_3_code' => 'EGY',
                'num_code' =>818,
            ],
            [
                'country_name' => 'El Salvador',
                'nationality' => 'Salvadoran',
                'alpha_2_code' => 'SV',
                'alpha_3_code' => 'SLV',
                'num_code' =>222,
            ],
            [
                'country_name' => 'Equatorial Guinea',
                'nationality' => 'Equatorial Guinean',
                'alpha_2_code' => 'GQ',
                'alpha_3_code' => 'GNQ',
                'num_code' =>226,
            ],
            [
                'country_name' => 'Eritrea',
                'nationality' => 'Eritrean',
                'alpha_2_code' => 'ER',
                'alpha_3_code' => 'ERI',
                'num_code' =>232,
            ],
            [
                'country_name' => 'Estonia',
                'nationality' => 'Estonian',
                'alpha_2_code' => 'EE',
                'alpha_3_code' => 'EST',
                'num_code' =>233,
            ],
            [
                'country_name' => 'Ethiopia',
                'nationality' => 'Ethiopian',
                'alpha_2_code' => 'ET',
                'alpha_3_code' => 'ETH',
                'num_code' =>231,
            ],
            [
                'country_name' => 'Falkland Islands (Malvinas)',
                'nationality' => 'Falkland Islander',
                'alpha_2_code' => 'FK',
                'alpha_3_code' => 'FLK',
                'num_code' =>238,
            ],
            [
                'country_name' => 'Faroe Islands',
                'nationality' => 'Faroese',
                'alpha_2_code' => 'FO',
                'alpha_3_code' => 'FRO',
                'num_code' =>234,
            ],
            [
                'country_name' => 'Fiji',
                'nationality' => 'Fijian',
                'alpha_2_code' => 'FJ',
                'alpha_3_code' => 'FJI',
                'num_code' =>242,
            ],
            [
                'country_name' => 'Finland',
                'nationality' => 'Finnish',
                'alpha_2_code' => 'FI',
                'alpha_3_code' => 'FIN',
                'num_code' =>246,
            ],
            [
                'country_name' => 'France',
                'nationality' => 'French',
                'alpha_2_code' => 'FR',
                'alpha_3_code' => 'FRA',
                'num_code' =>250,
            ],
            [
                'country_name' => 'French Guiana',
                'nationality' => 'French Guianese',
                'alpha_2_code' => 'GF',
                'alpha_3_code' => 'GUF',
                'num_code' =>254,
            ],
            [
                'country_name' => 'French Polynesia',
                'nationality' => 'French Polynesian',
                'alpha_2_code' => 'PF',
                'alpha_3_code' => 'PYF',
                'num_code' =>258,
            ],
            [
                'country_name' => 'French Southern Territories',
                'nationality' => 'French Southern Territories',
                'alpha_2_code' => 'TF',
                'alpha_3_code' => 'ATF',
                'num_code' =>260,
            ],
            [
                'country_name' => 'Gabon',
                'nationality' => 'Gabonese',
                'alpha_2_code' => 'GA',
                'alpha_3_code' => 'GAB',
                'num_code' =>266,
            ],
            [
                'country_name' => 'Gambia',
                'nationality' => 'Gambian',
                'alpha_2_code' => 'GM',
                'alpha_3_code' => 'GMB',
                'num_code' =>270,
            ],
            [
                'country_name' => 'Georgia',
                'nationality' => 'Georgian',
                'alpha_2_code' => 'GE',
                'alpha_3_code' => 'GEO',
                'num_code' =>268,
            ],
            [
                'country_name' => 'Germany',
                'nationality' => 'German',
                'alpha_2_code' => 'DE',
                'alpha_3_code' => 'DEU',
                'num_code' =>276,
            ],
            [
                'country_name' => 'Ghana',
                'nationality' => 'Ghanaian',
                'alpha_2_code' => 'GH',
                'alpha_3_code' => 'GHA',
                'num_code' =>288,
            ],
            [
                'country_name' => 'Gibraltar',
                'nationality' => 'Gibraltar',
                'alpha_2_code' => 'GI',
                'alpha_3_code' => 'GIB',
                'num_code' =>292,
            ],
            [
                'country_name' => 'Great Britain',
                'nationality' => 'British',
                'alpha_2_code' => 'GB',
                'alpha_3_code' => 'GBR',
                'num_code' => 826,
            ],
            [
                'country_name' => 'Greece',
                'nationality' => 'Greek',
                'alpha_2_code' => 'GR',
                'alpha_3_code' => 'GRC',
                'num_code' =>300,
            ],
            [
                'country_name' => 'Greenland',
                'nationality' => 'Greenlandic',
                'alpha_2_code' => 'GL',
                'alpha_3_code' => 'GRL',
                'num_code' =>304,
            ],
            [
                'country_name' => 'Grenada',
                'nationality' => 'Grenadian',
                'alpha_2_code' => 'GD',
                'alpha_3_code' => 'GRD',
                'num_code' =>308,
            ],
            [
                'country_name' => 'Guadeloupe',
                'nationality' => 'Guadeloupe',
                'alpha_2_code' => 'GP',
                'alpha_3_code' => 'GLP',
                'num_code' =>312,
            ],
            [
                'country_name' => 'Guam',
                'nationality' => 'Guamanian',
                'alpha_2_code' => 'GU',
                'alpha_3_code' => 'GUM',
                'num_code' =>316,
            ],
            [
                'country_name' => 'Guatemala',
                'nationality' => 'Guatemalan',
                'alpha_2_code' => 'GT',
                'alpha_3_code' => 'GTM',
                'num_code' =>320,
            ],
            [
                'country_name' => 'Guernsey',
                'nationality' => 'Channel Islander',
                'alpha_2_code' => 'GG',
                'alpha_3_code' => 'GGY',
                'num_code' =>831,
            ],
            [
                'country_name' => 'Guinea',
                'nationality' => 'Guinean',
                'alpha_2_code' => 'GN',
                'alpha_3_code' => 'GIN',
                'num_code' =>324,
            ],
            [
                'country_name' => 'Guinea-Bissau',
                'nationality' => 'Bissau-Guinean',
                'alpha_2_code' => 'GW',
                'alpha_3_code' => 'GNB',
                'num_code' =>624,
            ],
            [
                'country_name' => 'Guyana',
                'nationality' => 'Guyanese',
                'alpha_2_code' => 'GY',
                'alpha_3_code' => 'GUY',
                'num_code' =>328,
            ],
            [
                'country_name' => 'Haiti',
                'nationality' => 'Haitian',
                'alpha_2_code' => 'HT',
                'alpha_3_code' => 'HTI',
                'num_code' =>332,
            ],
            [
                'country_name' => 'Honduras',
                'nationality' => 'Honduran',
                'alpha_2_code' => 'HN',
                'alpha_3_code' => 'HND',
                'num_code' =>340,
            ],
            [
                'country_name' => 'Hong Kong',
                'nationality' => 'Hong Konger',
                'alpha_2_code' => 'HK',
                'alpha_3_code' => 'HKG',
                'num_code' =>344,
            ],
            [
                'country_name' => 'Hungary',
                'nationality' => 'Hungarian',
                'alpha_2_code' => 'HU',
                'alpha_3_code' => 'HUN',
                'num_code' =>348,
            ],
            [
                'country_name' => 'Iceland',
                'nationality' => 'Icelandic',
                'alpha_2_code' => 'IS',
                'alpha_3_code' => 'ISL',
                'num_code' =>352,
            ],
            [
                'country_name' => 'India',
                'nationality' => 'Indian',
                'alpha_2_code' => 'IN',
                'alpha_3_code' => 'IND',
                'num_code' =>356,
            ],
            [
                'country_name' => 'Indonesia',
                'nationality' => 'Indonesian',
                'alpha_2_code' => 'ID',
                'alpha_3_code' => 'IDN',
                'num_code' =>360,
            ],
            [
                'country_name' => 'Iran',
                'nationality' => 'Iranian',
                'alpha_2_code' => 'IR',
                'alpha_3_code' => 'IRN',
                'num_code' =>364,
            ],
            [
                'country_name' => 'Iraq',
                'nationality' => 'Iraqi',
                'alpha_2_code' => 'IQ',
                'alpha_3_code' => 'IRQ',
                'num_code' =>368,
            ],
            [
                'country_name' => 'Ireland',
                'nationality' => 'Irish',
                'alpha_2_code' => 'IE',
                'alpha_3_code' => 'IRL',
                'num_code' =>372,
            ],
            [
                'country_name' => 'Israel',
                'nationality' => 'Israeli',
                'alpha_2_code' => 'IL',
                'alpha_3_code' => 'ISR',
                'num_code' =>376,
            ],
            [
                'country_name' => 'Italy',
                'nationality' => 'Italian',
                'alpha_2_code' => 'IT',
                'alpha_3_code' => 'ITA',
                'num_code' =>380,
            ],
            [
                'country_name' => 'Jamaica',
                'nationality' => 'Jamaican',
                'alpha_2_code' => 'JM',
                'alpha_3_code' => 'JAM',
                'num_code' =>388,
            ],
            [
                'country_name' => 'Japan',
                'nationality' => 'Japanese',
                'alpha_2_code' => 'JP',
                'alpha_3_code' => 'JPN',
                'num_code' =>392,
            ],
            [
                'country_name' => 'Jordan',
                'nationality' => 'Jordanian',
                'alpha_2_code' => 'JO',
                'alpha_3_code' => 'JOR',
                'num_code' =>400,
            ],
            [
                'country_name' => 'Kazakhstan',
                'nationality' => 'Kazakh',
                'alpha_2_code' => 'KZ',
                'alpha_3_code' => 'KAZ',
                'num_code' =>398,
            ],
            [
                'country_name' => 'Kenya',
                'nationality' => 'Kenyan',
                'alpha_2_code' => 'KE',
                'alpha_3_code' => 'KEN',
                'num_code' =>404,
            ],
            [
                'country_name' => 'Kiribati',
                'nationality' => 'I-Kiribati',
                'alpha_2_code' => 'KI',
                'alpha_3_code' => 'KIR',
                'num_code' =>296,
            ],
            [
                'country_name' => 'Korea (Republic of)',
                'nationality' => 'South Korean',
                'alpha_2_code' => 'KR',
                'alpha_3_code' => 'KOR',
                'num_code' =>410,
            ],
            [
                'country_name' => 'Kuwait',
                'nationality' => 'Kuwaiti',
                'alpha_2_code' => 'KW',
                'alpha_3_code' => 'KWT',
                'num_code' =>414,
            ],
            [
                'country_name' => 'Kyrgyzstan',
                'nationality' => 'Kyrgyz',
                'alpha_2_code' => 'KG',
                'alpha_3_code' => 'KGZ',
                'num_code' =>417,
            ],
            [
                'country_name' =>"Lao People's Democratic Republic", 
                'nationality' => 'Lao',
                'alpha_2_code' => 'LA',
                'alpha_3_code' => 'LAO',
                'num_code' =>418,
            ],
            [
                'country_name' => 'Latvia',
                'nationality' => 'Latvian',
                'alpha_2_code' => 'LV',
                'alpha_3_code' => 'LVA',
                'num_code' =>428,
            ],
            [
                'country_name' => 'Lebanon',
                'nationality' => 'Lebanese',
                'alpha_2_code' => 'LB',
                'alpha_3_code' => 'LBN',
                'num_code' =>422,
            ],
            [
                'country_name' => 'Lesotho',
                'nationality' => 'Mosotho',
                'alpha_2_code' => 'LS',
                'alpha_3_code' => 'LSO',
                'num_code' =>426,
            ],
            [
                'country_name' => 'Liberia',
                'nationality' => 'Liberian',
                'alpha_2_code' => 'LR',
                'alpha_3_code' => 'LBR',
                'num_code' =>430,
            ],
            [
                'country_name' => 'Libya',
                'nationality' => 'Libyan',
                'alpha_2_code' => 'LY',
                'alpha_3_code' => 'LBY',
                'num_code' =>434,
            ],
            [
                'country_name' => 'Liechtenstein',
                'nationality' => 'Liechtenstein',
                'alpha_2_code' => 'LI',
                'alpha_3_code' => 'LIE',
                'num_code' =>438,
            ],
            [
                'country_name' => 'Lithuania',
                'nationality' => 'Lithuanian',
                'alpha_2_code' => 'LT',
                'alpha_3_code' => 'LTU',
                'num_code' =>440,
            ],
            [
                'country_name' => 'Luxembourg',
                'nationality' => 'Luxembourger',
                'alpha_2_code' => 'LU',
                'alpha_3_code' => 'LUX',
                'num_code' =>442,
            ],
            [
                'country_name' => 'Macao',
                'nationality' => 'Macanese',
                'alpha_2_code' => 'MO',
                'alpha_3_code' => 'MAC',
                'num_code' =>446,
            ],
            [
                'country_name' => 'Macedonia (the former Yugoslav Republic of)',
                'nationality' => 'Macedonian',
                'alpha_2_code' => 'MK',
                'alpha_3_code' => 'MKD',
                'num_code' =>807,
            ],
            [
                'country_name' => 'Madagascar',
                'nationality' => 'Malagasy',
                'alpha_2_code' => 'MG',
                'alpha_3_code' => 'MDG',
                'num_code' =>450,
            ],
            [
                'country_name' => 'Malawi',
                'nationality' => 'Malawian',
                'alpha_2_code' => 'MW',
                'alpha_3_code' => 'MWI',
                'num_code' =>454,
            ],
            [
                'country_name' => 'Malaysia',
                'nationality' => 'Malaysian',
                'alpha_2_code' => 'MY',
                'alpha_3_code' => 'MYS',
                'num_code' =>458,
            ],
            [
                'country_name' => 'Maldives',
                'nationality' => 'Maldivian',
                'alpha_2_code' => 'MV',
                'alpha_3_code' => 'MDV',
                'num_code' =>462,
            ],
            [
                'country_name' => 'Mali',
                'nationality' => 'Malian',
                'alpha_2_code' => 'ML',
                'alpha_3_code' => 'MLI',
                'num_code' =>466,
            ],
            [
                'country_name' => 'Malta',
                'nationality' => 'Maltese',
                'alpha_2_code' => 'MT',
                'alpha_3_code' => 'MLT',
                'num_code' =>470,
            ],
            [
                'country_name' => 'Marshall Islands',
                'nationality' => 'Marshallese',
                'alpha_2_code' => 'MH',
                'alpha_3_code' => 'MHL',
                'num_code' =>584,
            ],
            [
                'country_name' => 'Martinique',
                'nationality' => 'Martiniquais',
                'alpha_2_code' => 'MQ',
                'alpha_3_code' => 'MTQ',
                'num_code' =>474,
            ],
            [
                'country_name' => 'Mauritania',
                'nationality' => 'Mauritanian',
                'alpha_2_code' => 'MR',
                'alpha_3_code' => 'MRT',
                'num_code' =>478,
            ],
            [
                'country_name' => 'Mauritius',
                'nationality' => 'Mauritian',
                'alpha_2_code' => 'MU',
                'alpha_3_code' => 'MUS',
                'num_code' =>480,
            ],
            [
                'country_name' => 'Mayotte',
                'nationality' => 'Mahoran',
                'alpha_2_code' => 'YT',
                'alpha_3_code' => 'MYT',
                'num_code' =>175,
            ],
            [
                'country_name' => 'Mexico',
                'nationality' => 'Mexican',
                'alpha_2_code' => 'MX',
                'alpha_3_code' => 'MEX',
                'num_code' =>484,
            ],
            [
                'country_name' => 'Micronesia (Federated States of)',
                'nationality' => 'Micronesian',
                'alpha_2_code' => 'FM',
                'alpha_3_code' => 'FSM',
                'num_code' =>583,
            ],
            [
                'country_name' => 'Moldova (Republic of)',
                'nationality' => 'Moldovan',
                'alpha_2_code' => 'MD',
                'alpha_3_code' => 'MDA',
                'num_code' =>498,
            ],
            [
                'country_name' => 'Mongolia',
                'nationality' => 'Mongolian',
                'alpha_2_code' => 'MN',
                'alpha_3_code' => 'MNG',
                'num_code' =>496,
            ],
            [
                'country_name' => 'Montenegro',
                'nationality' => 'Montenegrin',
                'alpha_2_code' => 'ME',
                'alpha_3_code' => 'MNE',
                'num_code' =>499,
            ],
            [
                'country_name' => 'Montserrat',
                'nationality' => 'Montserratian',
                'alpha_2_code' => 'MS',
                'alpha_3_code' => 'MSR',
                'num_code' =>500,
            ],
            [
                'country_name' => 'Morocco',
                'nationality' => 'Moroccan',
                'alpha_2_code' => 'MA',
                'alpha_3_code' => 'MAR',
                'num_code' =>504,
            ],
            [
                'country_name' => 'Mozambique',
                'nationality' => 'Mozambican',
                'alpha_2_code' => 'MZ',
                'alpha_3_code' => 'MOZ',
                'num_code' =>508,
            ],
            [
                'country_name' => 'Myanmar',
                'nationality' => 'Burmese',
                'alpha_2_code' => 'MM',
                'alpha_3_code' => 'MMR',
                'num_code' =>104,
            ],
            [
                'country_name' => 'Namibia',
                'nationality' => 'Namibian',
                'alpha_2_code' => 'NA',
                'alpha_3_code' => 'NAM',
                'num_code' =>516,
            ],
            [
                'country_name' => 'Nauru',
                'nationality' => 'Nauruan',
                'alpha_2_code' => 'NR',
                'alpha_3_code' => 'NRU',
                'num_code' =>520,
            ],
            [
                'country_name' => 'Nepal',
                'nationality' => 'Nepalese',
                'alpha_2_code' => 'NP',
                'alpha_3_code' => 'NPL',
                'num_code' =>524,
            ],
            [
                'country_name' => 'Netherlands',
                'nationality' => 'Dutch',
                'alpha_2_code' => 'NL',
                'alpha_3_code' => 'NLD',
                'num_code' =>528,
            ],
            [
                'country_name' => 'New Caledonia',
                'nationality' => 'New Caledonian',
                'alpha_2_code' => 'NC',
                'alpha_3_code' => 'NCL',
                'num_code' =>540,
            ],
            [
                'country_name' => 'New Zealand',
                'nationality' => 'New Zealander',
                'alpha_2_code' => 'NZ',
                'alpha_3_code' => 'NZL',
                'num_code' =>554,
            ],
            [
                'country_name' => 'Nicaragua',
                'nationality' => 'Nicaraguan',
                'alpha_2_code' => 'NI',
                'alpha_3_code' => 'NIC',
                'num_code' =>558,
            ],
            [
                'country_name' => 'Niger',
                'nationality' => 'Nigerien',
                'alpha_2_code' => 'NE',
                'alpha_3_code' => 'NER',
                'num_code' =>562,
            ],
            [
                'country_name' => 'Nigeria',
                'nationality' => 'Nigerian',
                'alpha_2_code' => 'NG',
                'alpha_3_code' => 'NGA',
                'num_code' =>566,
            ],
            [
                'country_name' => 'Niue',
                'nationality' => 'Niuean',
                'alpha_2_code' => 'NU',
                'alpha_3_code' => 'NIU',
                'num_code' =>570,
            ],
            [
                'country_name' => 'Norfolk Island',
                'nationality' => 'Norfolk Islander',
                'alpha_2_code' => 'NF',
                'alpha_3_code' => 'NFK',
                'num_code' =>574,
            ],
            [
                'country_name' => "North Korea",
                'nationality' => 'North Korean',
                'alpha_2_code' => 'KP',
                'alpha_3_code' => 'PRK',
                'num_code' =>408,
            ],
            [
                'country_name' => 'Northern Mariana Islands',
                'nationality' => 'Northern Marianan',
                'alpha_2_code' => 'MP',
                'alpha_3_code' => 'MNP',
                'num_code' =>580,
            ],
            [
                'country_name' => 'Norway',
                'nationality' => 'Norwegian',
                'alpha_2_code' => 'NO',
                'alpha_3_code' => 'NOR',
                'num_code' =>578,
            ],
            [
                'country_name' => 'Oman',
                'nationality' => 'Omani',
                'alpha_2_code' => 'OM',
                'alpha_3_code' => 'OMN',
                'num_code' =>512,
            ],
            [
                'country_name' => 'Pakistan',
                'nationality' => 'Pakistani',
                'alpha_2_code' => 'PK',
                'alpha_3_code' => 'PAK',
                'num_code' =>586,
            ],
            [
                'country_name' => 'Palau',
                'nationality' => 'Palauan',
                'alpha_2_code' => 'PW',
                'alpha_3_code' => 'PLW',
                'num_code' =>585,
            ],
            [
                'country_name' => 'Palestine',
                'nationality' => 'Palestinian',
                'alpha_2_code' => 'PS',
                'alpha_3_code' => 'PSE',
                'num_code' =>275,
            ],
            [
                'country_name' => 'Panama',
                'nationality' => 'Panamanian',
                'alpha_2_code' => 'PA',
                'alpha_3_code' => 'PAN',
                'num_code' =>591,
            ],
            [
                'country_name' => 'Papua New Guinea',
                'nationality' => 'Papua New Guinean',
                'alpha_2_code' => 'PG',
                'alpha_3_code' => 'PNG',
                'num_code' =>598,
            ],
            [
                'country_name' => 'Paraguay',
                'nationality' => 'Paraguayan',
                'alpha_2_code' => 'PY',
                'alpha_3_code' => 'PRY',
                'num_code' =>600,
            ],
            [
                'country_name' => 'Peru',
                'nationality' => 'Peruvian',
                'alpha_2_code' => 'PE',
                'alpha_3_code' => 'PER',
                'num_code' =>604,
            ],
            [
                'country_name' => 'Philippines',
                'nationality' => 'Filipino',
                'alpha_2_code' => 'PH',
                'alpha_3_code' => 'PHL',
                'num_code' =>608,
            ],
            [
                'country_name' => 'Pitcairn',
                'nationality' => 'Pitcairn Islander',
                'alpha_2_code' => 'PN',
                'alpha_3_code' => 'PCN',
                'num_code' =>612,
            ],
            [
                'country_name' => 'Poland',
                'nationality' => 'Polish',
                'alpha_2_code' => 'PL',
                'alpha_3_code' => 'POL',
                'num_code' =>616,
            ],
            [
                'country_name' => 'Portugal',
                'nationality' => 'Portuguese',
                'alpha_2_code' => 'PT',
                'alpha_3_code' => 'PRT',
                'num_code' =>620,
            ],
            [
                'country_name' => 'Puerto Rico',
                'nationality' => 'Puerto Rican',
                'alpha_2_code' => 'PR',
                'alpha_3_code' => 'PRI',
                'num_code' =>630,
            ],
            [
                'country_name' => 'Qatar',
                'nationality' => 'Qatari',
                'alpha_2_code' => 'QA',
                'alpha_3_code' => 'QAT',
                'num_code' =>634,
            ],
            [
                'country_name' => 'Réunion',
                'nationality' => 'Réunionese',
                'alpha_2_code' => 'RE',
                'alpha_3_code' => 'REU',
                'num_code' =>638,
            ],
            [
                'country_name' => 'Romania',
                'nationality' => 'Romanian',
                'alpha_2_code' => 'RO',
                'alpha_3_code' => 'ROU',
                'num_code' =>642,
            ],
            [
                'country_name' => 'Russian Federation',
                'nationality' => 'Russian',
                'alpha_2_code' => 'RU',
                'alpha_3_code' => 'RUS',
                'num_code' =>643,
            ],
            [
                'country_name' => 'Rwanda',
                'nationality' => 'Rwandan',
                'alpha_2_code' => 'RW',
                'alpha_3_code' => 'RWA',
                'num_code' =>646,
            ],
            [
                'country_name' => 'Saint Barthélemy',
                'nationality' => 'Barthélemois',
                'alpha_2_code' => 'BL',
                'alpha_3_code' => 'BLM',
                'num_code' =>652,
            ],
            [
                'country_name' =>'Saint Helena',
                'nationality' => 'Saint Helenian',
                'alpha_2_code' => 'SH',
                'alpha_3_code' => 'SHN',
                'num_code' =>654,
       
            ],
            [
                'country_name' => 'Saint Kitts and Nevis',
                'nationality' => 'Kittitian/Nevisian',
                'alpha_2_code' => 'KN',
                'alpha_3_code' => 'KNA',
                'num_code' =>659,
            ],
            [
                'country_name' => 'Saint Lucia',
                'nationality' => 'Saint Lucian',
                'alpha_2_code' => 'LC',
                'alpha_3_code' => 'LCA',
                'num_code' =>662,
            ],
            [
                'country_name' => 'Saint Martin (French part)',
                'nationality' => 'Saint-Martinoise',
                'alpha_2_code' => 'MF',
                'alpha_3_code' => 'MAF',
                'num_code' =>663,
            ],
            [
                'country_name' => 'Saint Pierre and Miquelon',
                'nationality' => 'Saint-Pierrais/Miquelonnais',
                'alpha_2_code' => 'PM',
                'alpha_3_code' => 'SPM',
                'num_code' =>666,
            ],
            [
                'country_name' => 'Saint Vincent and the Grenadines',
                'nationality' => 'Vincentian"',
                'alpha_2_code' => 'VC',
                'alpha_3_code' => 'VCT',
                'num_code' =>670,
                
       
            ],
            [
                'country_name' => 'Samoa',
                'nationality' => 'Samoan',
                'alpha_2_code' => 'WS',
                'alpha_3_code' => 'WSM',
                'num_code' =>882,
            ],
            [
                'country_name' => 'San Marino',
                'nationality' => 'Sammarinese',
                'alpha_2_code' => 'SM',
                'alpha_3_code' => 'SMR',
                'num_code' =>674,
            ],
            [
                'country_name' => 'Sao Tome and Principe',
                'nationality' => 'São Toméan',
                'alpha_2_code' => 'ST',
                'alpha_3_code' => 'STP',
                'num_code' =>678,
            ],
            [
                'country_name' => 'Saudi Arabia',
                'nationality' => 'Saudi Arabian',
                'alpha_2_code' => 'SA',
                'alpha_3_code' => 'SAU',
                'num_code' =>682,
            ],
            [
                'country_name' => 'Senegal',
                'nationality' => 'Senegalese',
                'alpha_2_code' => 'SN',
                'alpha_3_code' => 'SEN',
                'num_code' =>686,
            ],
            [
                'country_name' => 'Serbia',
                'nationality' => 'Serbian',
                'alpha_2_code' => 'RS',
                'alpha_3_code' => 'SRB',
                'num_code' =>688,
            ],
            [
                'country_name' => 'Seychelles',
                'nationality' => 'Seychellois',
                'alpha_2_code' => 'SC',
                'alpha_3_code' => 'SYC',
                'num_code' =>690,
            ],
            [
                'country_name' => 'Sierra Leone',
                'nationality' => 'Sierra Leonean',
                'alpha_2_code' => 'SL',
                'alpha_3_code' => 'SLE',
                'num_code' =>694,
            ],
            [
                'country_name' => 'Singapore',
                'nationality' => 'Singaporean',
                'alpha_2_code' => 'SG',
                'alpha_3_code' => 'SGP',
                'num_code' =>702,
            ],
            [
                'country_name' => 'Sint Maarten (Dutch part)',
                'nationality' => 'Sint Maarten',
                'alpha_2_code' => 'SX',
                'alpha_3_code' => 'SXM',
                'num_code' =>534,
            ],
            [
                'country_name' => 'Slovakia',
                'nationality' => 'Slovak',
                'alpha_2_code' => 'SK',
                'alpha_3_code' => 'SVK',
                'num_code' =>703,
            ],
            [
                'country_name' => 'Slovenia',
                'nationality' => 'Slovenian',
                'alpha_2_code' => 'SI',
                'alpha_3_code' => 'SVN',
                'num_code' =>705,
            ],
            [
                'country_name' => 'Solomon Islands',
                'nationality' => 'Solomon Islander',
                'alpha_2_code' => 'SB',
                'alpha_3_code' => 'SLB',
                'num_code' =>90,
            ],
            [
                'country_name' => 'Somalia',
                'nationality' => 'Somali',
                'alpha_2_code' => 'SO',
                'alpha_3_code' => 'SOM',
                'num_code' =>706,
            ],
            [
                'country_name' => 'South Africa',
                'nationality' => 'South African',
                'alpha_2_code' => 'ZA',
                'alpha_3_code' => 'ZAF',
                'num_code' =>710,
            ],
            [
                'country_name' =>'South Georgia and the South Sandwich Islands',
                'nationality' => 'South Georgia/South',
                'alpha_2_code' => 'GS',
                'alpha_3_code' => 'SGS',
                'num_code' =>239
            ],
            [
                'country_name' => 'South Sudan',
                'nationality' => 'South Sudanese',
                'alpha_2_code' => 'SS',
                'alpha_3_code' => 'SSD',
                'num_code' =>728,
            ],
            [
                'country_name' => 'Spain',
                'nationality' => 'Spanish',
                'alpha_2_code' => 'ES',
                'alpha_3_code' => 'ESP',
                'num_code' =>724,
            ],
            [
                'country_name' => 'Sri Lanka',
                'nationality' => 'Sri Lankan',
                'alpha_2_code' => 'LK',
                'alpha_3_code' => 'LKA',
                'num_code' =>144,
            ],
            [
                'country_name' => 'Sudan',
                'nationality' => 'Sudanese',
                'alpha_2_code' => 'SD',
                'alpha_3_code' => 'SDN',
                'num_code' =>729,
            ],
            [
                'country_name' => 'Suriname',
                'nationality' => 'Surinamese',
                'alpha_2_code' => 'SR',
                'alpha_3_code' => 'SUR',
                'num_code' =>740,
            ],
            [
                'country_name' => 'Svalbard and Jan Mayen',
                'nationality' => 'Svalbard',
                'alpha_2_code' => 'SJ',
                'alpha_3_code' => 'SJM',
                'num_code' =>744,
            ],
            [
                'country_name' => 'Swaziland',
                'nationality' => 'Swazi',
                'alpha_2_code' => 'SZ',
                'alpha_3_code' => 'SWZ',
                'num_code' =>748,
            ],
            [
                'country_name' => 'Sweden',
                'nationality' => 'Swedish',
                'alpha_2_code' => 'SE',
                'alpha_3_code' => 'SWE',
                'num_code' =>752,
            ],
            [
                'country_name' => 'Switzerland',
                'nationality' => 'Swiss',
                'alpha_2_code' => 'CH',
                'alpha_3_code' => 'CHE',
                'num_code' =>756,
            ],
            [
                'country_name' => 'Syrian Arab Republic',
                'nationality' => 'Syrian',
                'alpha_2_code' => 'SY',
                'alpha_3_code' => 'SYR',
                'num_code' =>760,
            ],
            [
                'country_name' => 'Taiwan, Province of China',
                'nationality' => 'Taiwanese',
                'alpha_2_code' => 'TW',
                'alpha_3_code' => 'TWN',
                'num_code' =>158,
            ],
            [
                'country_name' => 'Tajikistan',
                'nationality' => 'Tajikistani',
                'alpha_2_code' => 'TJ',
                'alpha_3_code' => 'TJK',
                'num_code' =>762,
            ],
            [
                'country_name' => "Tanzania, United Republic of",
                'nationality' => 'Tanzanian',
                'alpha_2_code' => 'TZ',
                'alpha_3_code' => 'TZA',
                'num_code' =>834,
            ],
            [
                'country_name' => 'Thailand',
                'nationality' => 'Thai',
                'alpha_2_code' => 'TH',
                'alpha_3_code' => 'THA',
                'num_code' =>764,
            ],
            [
                'country_name' => 'Timor-Leste',
                'nationality' => 'Timorese',
                'alpha_2_code' => 'TL',
                'alpha_3_code' => 'TLS',
                'num_code' =>626,
            ],
            [
                'country_name' => 'Togo',
                'nationality' => 'Togolese',
                'alpha_2_code' => 'TG',
                'alpha_3_code' => 'TGO',
                'num_code' =>768,
            ],
            [
                'country_name' => 'Tokelau',
                'nationality' => 'Tokelauan',
                'alpha_2_code' => 'TK',
                'alpha_3_code' => 'TKL',
                'num_code' =>772,
            ],
            [
                'country_name' => 'Tonga',
                'nationality' => 'Tongan',
                'alpha_2_code' => 'TO',
                'alpha_3_code' => 'TON',
                'num_code' =>776,
            ],
            [
                'country_name' => 'Trinidad and Tobago',
                'nationality' => 'Trinidadian/Tobagonian',
                'alpha_2_code' => 'TT',
                'alpha_3_code' => 'TTO',
                'num_code' =>780,
            ],
            [
                'country_name' => 'Tunisia',
                'nationality' => 'Tunisian',
                'alpha_2_code' => 'TN',
                'alpha_3_code' => 'TUN',
                'num_code' =>788,
            ],
            [
                'country_name' => 'Turkey',
                'nationality' => 'Turkish',
                'alpha_2_code' => 'TR',
                'alpha_3_code' => 'TUR',
                'num_code' =>792,
            ],
            [
                'country_name' => 'Turkmenistan',
                'nationality' => 'Turkmen',
                'alpha_2_code' => 'TM',
                'alpha_3_code' => 'TKM',
                'num_code' =>795,
            ],
            [
                'country_name' => 'Turks and Caicos Islands',
                'nationality' => 'Turks and Caicos Islander',
                'alpha_2_code' => 'TC',
                'alpha_3_code' => 'TCA',
                'num_code' =>796,
            ],
            [
                'country_name' => 'Tuvalu',
                'nationality' => 'Tuvaluan',
                'alpha_2_code' => 'TV',
                'alpha_3_code' => 'TUV',
                'num_code' =>798,
            ],
            [
                'country_name' => "Uganda",
                'nationality' => "Ugandan",
                'alpha_2_code' => 'UG',
                'alpha_3_code' => 'UGA',
                'num_code' =>800,
            ],
            [
                'country_name' => 'Ukraine',
                'nationality' => 'Ukrainian',
                'alpha_2_code' => 'UA',
                'alpha_3_code' => 'UKR',
                'num_code' =>804,
            ],
            [
                'country_name' => 'United Arab Emirates',
                'nationality' => 'Emirati',
                'alpha_2_code' => 'AE',
                'alpha_3_code' => 'UAE',
                'num_code' =>784,
            ],
            [
                'country_name' => 'United States of America',
                'nationality' => 'American',
                'alpha_2_code' => 'US',
                'alpha_3_code' => 'USA',
                'num_code' =>840,
            ],
            [
                'country_name' => 'Uruguay',
                'nationality' => 'Uruguayan',
                'alpha_2_code' => 'UY',
                'alpha_3_code' => 'URY',
                'num_code' =>858,
            ],
            [
                'country_name' => 'Uzbekistan',
                'nationality' => 'Uzbek',
                'alpha_2_code' => 'UZ',
                'alpha_3_code' => 'UZB',
                'num_code' =>860,
            ],
            [
                'country_name' => 'Vanuatu',
                'nationality' => 'Vanuatuan',
                'alpha_2_code' => 'VU',
                'alpha_3_code' => 'VUT',
                'num_code' =>548,
            ],
            [
                'country_name' => 'Vatican City State',
                'nationality' => 'Vatican citizen',
                'alpha_2_code' => 'VA',
                'alpha_3_code' => 'VAT',
                'num_code' =>336,
            ],
            [
                'country_name' => 'Venezuela (Bolivarian Republic of)',
                'nationality' => 'Venezuelan',
                'alpha_2_code' => 'VE',
                'alpha_3_code' => 'VEN',
                'num_code' =>862,
            ],
            [
                'country_name' => 'Vietnam',
                'nationality' => 'Vietnamese',
                'alpha_2_code' => 'VN',
                'alpha_3_code' => 'VNM',
                'num_code' =>704,
            ],
            [
                'country_name' => 'Virgin Islands (British)',
                'nationality' => 'British Virgin Islander',
                'alpha_2_code' => 'VG',
                'alpha_3_code' => 'VGB',
                'num_code' =>92,
            ],
            [
                'country_name' => 'Virgin Islands (U.S.)',
                'nationality' => 'U.S. Virgin Islander',
                'alpha_2_code' => 'VI',
                'alpha_3_code' => 'VIR',
                'num_code' =>850,
            ],
            [
                'country_name' => 'Wallis and Futuna',
                'nationality' => 'Wallisian/Futunan',                
                'alpha_2_code' => 'WF',
                'alpha_3_code' => 'WLF',
                'num_code' =>876,
       
            ],
            [
                'country_name' => 'Western Sahara',
                'nationality' => 'Sahrawi',
                'alpha_2_code' => 'EH',
                'alpha_3_code' => 'ESH',
                'num_code' =>732,
            ],
            [
                'country_name' => 'Yemen',
                'nationality' => 'Yemeni',
                'alpha_2_code' => 'YE',
                'alpha_3_code' => 'YEM',
                'num_code' =>887,
            ],
            [
                'country_name' => 'Zambia',
                'nationality' => 'Zambian',
                'alpha_2_code' => 'ZM',
                'alpha_3_code' => 'ZMB',
                'num_code' =>894,
            ],
            [
                'country_name' => 'Zimbabwe',
                'nationality' => 'Zimbabwean',
                'alpha_2_code' => 'ZW',
                'alpha_3_code' => 'ZWE',
                'num_code' =>716,
            ],
        ];
        $nationality->insertBatch($data);
    }
}
