<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use App\Models\ParticularModel;

class ParticularSeeder extends Seeder
{
    public function run()
    {
        $particularModel = new ParticularModel();
        $data = [
            // assets particulars
            [
                'particular_name' => 'Cash',
                'particular_slug' => 'cash',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 1,
                'subcategory_id' => 1,
                'account_typeId' => 1,
                'cash_flow_typeId' => 2,
            ],
            [
                'particular_name' => 'Bank',
                'particular_slug' => 'bank',
                'category_id' => 1,
                'subcategory_id' => 1,
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'account_typeId' => 1,
                'cash_flow_typeId' => 2,
            ],
            [
                'particular_name' => 'Lender Investments',
                'particular_slug' => 'lender-investments',
                'category_id' => 1,
                'subcategory_id' => 1,
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'account_typeId' => 2,
                'cash_flow_typeId' => 2,
            ],
            [
                'particular_name' => 'Gross Loans ~ Principal',
                'particular_slug' => 'gross-loans-principal',
                'category_id' => 1,
                'subcategory_id' => 1,
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'account_typeId' => 3,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Receivable ~ Interest on Loans',
                'particular_slug' => 'receivable-interest-on-loans',
                'category_id' => 1,
                'subcategory_id' => 1,
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'account_typeId' => 4,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Receivable ~ Fee and Commission Loans',
                'particular_slug' => 'receivable-fee-and-commission-loans',
                'category_id' => 1,
                'subcategory_id' => 1,
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'account_typeId' => 4,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Receivable ~ Penalty Loans',
                'particular_slug' => 'receivable-penalty-on-loans',
                'category_id' => 1,
                'subcategory_id' => 1,
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'account_typeId' => 4,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Receivable ~ Revenue on Client Saving Deposit',
                'particular_slug' => 'receivable-revenue-on-client-saving-deposit',
                'category_id' => 1,
                'subcategory_id' => 1,
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'account_typeId' => 4,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Receivable ~ Revenue on Investor Deposit',
                'particular_slug' => 'receivable-revenue-on-investor-deposit',
                'category_id' => 1,
                'subcategory_id' => 1,
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'account_typeId' => 4,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Receivable ~ Non Operating Revenue',
                'particular_slug' => 'receivable-non-operating-revenue',
                'category_id' => 1,
                'subcategory_id' => 1,
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'account_typeId' => 4,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Computers',
                'particular_slug' => 'computers',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 1,
                'subcategory_id' => 2,
                'account_typeId' => 7,
                'cash_flow_typeId' => 6
            ],
            // equity particulars
            [
                'particular_name' => 'Starter Up Capital',
                'particular_slug' => 'starter-up-capital',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 2,
                'subcategory_id' => 3,
                'account_typeId' => 8,
                'cash_flow_typeId' => 3,
            ],
            [
                'particular_name' => 'Share Capital',
                'particular_slug' => 'share-capital',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 2,
                'subcategory_id' => 3,
                'account_typeId' => 8,
                'cash_flow_typeId' => 3,
            ],
            [
                'particular_name' => 'Retained Earnings',
                'particular_slug' => 'retained-earnings',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 2,
                'subcategory_id' => 4,
                'account_typeId' => 8,
                'cash_flow_typeId' => 6,
            ],
            // liability particulars
            [
                'particular_name' => 'Payable ~ Client Saving Deposit',
                'particular_slug' => 'payable-client-saving-deposit',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 6,
                'account_typeId' => 16,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Payable ~ Investor Deposit',
                'particular_slug' => 'payable-investor-deposit',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 6,
                'account_typeId' => 16,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Payable ~ Merchant Borrowings',
                'particular_slug' => 'payable-merchant-borrowings',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 5,
                'account_typeId' => 16,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Payable ~ Payroll Expenses',
                'particular_slug' => 'payable-payroll-expenses',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 6,
                'account_typeId' => 16,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Payable ~ Non Operating Expenses',
                'particular_slug' => 'payable-non-operating-expenses',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 6,
                'account_typeId' => 16,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Payable ~ Miscellaneous Expenses',
                'particular_slug' => 'payable-miscellaneous-expenses',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 6,
                'account_typeId' => 16,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Client Savings',
                'particular_slug' => 'client-savings',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 6,
                'account_typeId' => 12,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Investor Deposit',
                'particular_slug' => 'investor-deposit',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 6,
                'account_typeId' => 13,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Accumulated Loan Impairment',
                'particular_slug' => 'accumulated-loan-impairment',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 5,
                'account_typeId' => 11,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Accumulated Depreciation and Amortization',
                'particular_slug' => 'accumulated-depreciation-and-amortization',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 5,
                'account_typeId' => 10,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Income Tax Liability',
                'particular_slug' => 'icome-tax-liability',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 6,
                'account_typeId' => 14,
                'cash_flow_typeId' => 5,
            ],
            // revenue particulars
            [
                'particular_name' => 'Loan Application Fees',
                'particular_slug' => 'loan-application-fees',
                'charged' => 'yes',
                'charge' => '20000',
                'charge_method' => 'Amount',
                'charge_mode' => 'Manual',
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 4,
                'subcategory_id' => 7,
                'account_typeId' => 18,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Loan Processing Fees',
                'particular_slug' => 'loan-processing-fees',
                'charged' => 'yes',
                'charge' => '1',
                'charge_method' => 'Percent',
                'charge_mode' => 'Auto',
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 4,
                'subcategory_id' => 7,
                'account_typeId' => 18,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Loan Appraisal Fees',
                'particular_slug' => 'loan-appraisal-fees',
                'charged' => 'yes',
                'charge' => '1',
                'charge_method' => 'Percent',
                'charge_mode' => 'Auto',
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 4,
                'subcategory_id' => 7,
                'account_typeId' => 18,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Loan Cash Cover',
                'particular_slug' => 'loan-cash-cover',
                'charged' => 'yes',
                'charge' => '10',
                'charge_method' => 'Percent',
                'charge_mode' => 'Auto',
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 3,
                'subcategory_id' => 6,
                'account_typeId' => 18,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Interest on Loans',
                'particular_slug' => 'interest-on-loans',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 4,
                'subcategory_id' => 7,
                'account_typeId' => 19,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Fees and Commission on Loans',
                'particular_slug' => 'fess-and-commission-on-loans',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 4,
                'subcategory_id' => 7,
                'account_typeId' => 19,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Penalties on Loans',
                'particular_slug' => 'penalties-on-loans',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 4,
                'subcategory_id' => 7,
                'account_typeId' => 19,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Revenue from Client Saving Deposits',
                'particular_slug' => 'revenue-from-client-saving-deposits',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 4,
                'subcategory_id' => 7,
                'account_typeId' => 20,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Revenue from Investor Deposits',
                'particular_slug' => 'revenue-from-investor-deposits',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 4,
                'subcategory_id' => 7,
                'account_typeId' => 20,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Non Operating Revenue',
                'particular_slug' => 'non-operating-revenue',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 4,
                'subcategory_id' => 8,
                'account_typeId' => 22,
                'cash_flow_typeId' => 4,
            ],
            [
                'particular_name' => 'Subsidy',
                'particular_slug' => 'subsidy',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 4,
                'subcategory_id' => 8,
                'account_typeId' => 23,
                'cash_flow_typeId' => 3,
            ],
            [
                'particular_name' => 'Client Membership',
                'particular_slug' => 'client-membership',
                'charged' => 'Yes',
                'charge' => '20000',
                'charge_method' => 'Amount',
                'charge_mode' => 'Manual',
                'charge_frequency' => 'One-time',
                'grace_period' => '0',
                'category_id' => 4,
                'subcategory_id' => 7,
                'account_typeId' => 24,
                'cash_flow_typeId' => 3,
            ],
            // expense particulars
            [
                'particular_name' => 'Provision for Impairment ~ Loan Principal',
                'particular_slug' => 'provision-for-impairment-loan-principal',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 33,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Provision for Impairment ~ Interest loan',
                'particular_slug' => 'provision-for-impairment-interest-loan',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 33,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Provision for Impairment ~ Fees and Commission on Loans',
                'particular_slug' => 'provision-for-impairment-feess-and-commisson-on-loans',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 33,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Provision for Impairment ~ Penalty on Loans',
                'particular_slug' => 'provision-for-impairment-loan-penalty-on-loans',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 33,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Default ~ Loans Principal',
                'particular_slug' => 'default-loans-principal',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 26,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Default ~ Interest on Loans',
                'particular_slug' => 'default-interest-on-loans',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 26,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Default ~ Fees and Commission on Loans',
                'particular_slug' => 'default-fees-and-commission-on-loans',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 26,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Default ~ Penalty on Loans',
                'particular_slug' => 'default-penalty-on-loans',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 26,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Depreciation and Amortization Expenses',
                'particular_slug' => 'depreciation-and-amortization-expenses',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 27,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Restructured ~ Loan Principal',
                'particular_slug' => 'restructured-loan-principal',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 34,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Restructured ~ Interest on Loans',
                'particular_slug' => 'restructured-interest-on-loans',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 34,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Restructured ~ Fees and Commission on Loans',
                'particular_slug' => 'restructured-fees and-commission-on-loans',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 34,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Restructured ~ Penalty on Loans',
                'particular_slug' => 'restructured-penalty-on-loans',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 34,
                'cash_flow_typeId' => 6,
            ],
            [
                'particular_name' => 'Loss(or Gain) on Asset Disposal',
                'particular_slug' => 'loss(or-gain)-on-asset-disposal',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 25,
                'cash_flow_typeId' => 1,
            ],
            
            [
                'particular_name' => 'Payroll Expenses',
                'particular_slug' => 'payroll-expenses',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 31,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Exchange Rete Losses(or Gains)',
                'particular_slug' => 'exchange-rate-losses(or-gains)',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 31,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Expenses on Client Savings Deposits',
                'particular_slug' => 'expenses-on-client-savings-deposits',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 29,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Expenses on Investor Deposits',
                'particular_slug' => 'expenses-on-investor-deposits',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 29,
                'cash_flow_typeId' => 1,
            ],
            [
                'particular_name' => 'Expenses on Merchant Borrowings',
                'particular_slug' => 'expenses-on-merchant-borrowings',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 30,
                'cash_flow_typeId' => 3,
            ],
            [
                'particular_name' => 'Non Operating Expenses',
                'particular_slug' => 'non-operating-expenses',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 32,
                'cash_flow_typeId' => 4,
            ],
            [
                'particular_name' => 'Income Tax Expense',
                'particular_slug' => 'income-tax-expense',
                'charged' => 'No',
                'charge' => null,
                'charge_method' => null,
                'charge_mode' => null,
                'charge_frequency' => null,
                'grace_period' => null,
                'category_id' => 5,
                'subcategory_id' => 9,
                'account_typeId' => 35,
                'cash_flow_typeId' => 5,
            ],
        ];
        $particularModel->insertBatch($data);
    }
}
